name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          echo $(docker-compose --version)

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      # - name: Build and start the environment
      #   run: |
      #     docker-compose up -d --build

      - name: Install Lingua Franca
        run: curl -Ls https://install.lf-lang.org | bash -s cli

      - name: Build the Test Publisher
        run: |
          (cd InfluxPublisher && bash run_build.sh)

      - name: Start Test Publisher environment
        run: |
          (cd InfluxPublisher && docker compose up -d --build)

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Run E2E Tests
        run: |
          (cd InfluxPublisher/tests && bash test_publisher_e2e.sh)

      - name: Tear down Docker containers
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f ./InfluxPublisher/docker-compose.yml down
